### ISSUE TITLE
search count can be off

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/cdli1#10]
Search count seems to take into account only some instances of search string in texts. 
eg :  "SZU+LAGAB" =>  28,571 instances
counting them manually  => 31,000+

**Comment by sohnyrin** [comment]
Bob: I checked and that is certainly due to the counter and highlighter not picking up multiple instances of a searched sign in a single line

**Comment by epageperron** [comment]
This issue was moved to cdli-gh/Framework#5
